services:
  mews-plugin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mews-plugin
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_ADDR=host.docker.internal:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./index.html:/app/index.html  # Mount HTML for development purposes
    restart: unless-stopped  # Keep webhook server running